services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=reviews_user
      - MYSQL_PASSWORD=m0v13s
      - MYSQL_DATABASE=reviews_db
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_USER=reviews_user
      - MYSQL_PASSWORD=m0v13s
      - MYSQL_DATABASE=reviews_db
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - ./reviews.sql:/docker-entrypoint-initdb.d/reviews.sql
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: